server: 
  port: 7001
 
spirng:
  application:
    name: leo-euraka-server
      
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      