spring:
   application:
    name: microservicecloud-consumer-feign

server:
  port: 81
  
eureka:
  client: #客户端注册进eureka服务列表内
    #register-with-eureka: false #是否注册
    serviceUrl: 
       defaultZone: http://localhost:7001/eureka 
  instance:
    instance-id: microservicecloud-consumer-user-feign-81
    prefer-ip-address: true     #访问路径可以显示IP地址       

feign: 
  hystrix: 
    enabled: true

info: 
  app.name: leo-microservicecloud
  company.name: www.leo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$